repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: no-commit-to-branch
        args: [--branch, main]

  - repo: https://github.com/bmorcos/pre-commit-hooks-cpp
    rev: master # Or a specific commit/tag for stability
    hooks:
      - id: clang-format
        args: [--style=Google] # Or your preferred style
      - id: cpplint
        args: [--filter=-legal/copyright] # Adjust filters as needed
      - id: cppcheck
        args: [--enable=warning]
